name: Homebrew Formula Check

on:
  push:
    paths:
      - 'ton.rb'  # trigger this action only when ton.rb is modified
    branches:
      - main
  pull_request:
    paths:
      - 'ton.rb'  # also on PRs that modify ton.rb
    branches:
      - main

jobs:
  brew_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install formula dependencies
        run: brew install --only-dependencies ton

      - name: Audit formula
        run: brew audit --strict ton

      - name: Test formula
        run: brew test ton
